# Generated by Django 5.2.7 on 2025-11-11 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE administration_user 
                ADD COLUMN IF NOT EXISTS avatar_s3_key VARCHAR(500),
                ADD COLUMN IF NOT EXISTS avatar_s3_bucket VARCHAR(100);
            """,
            reverse_sql="""
                ALTER TABLE administration_user 
                DROP COLUMN IF EXISTS avatar_s3_key,
                DROP COLUMN IF EXISTS avatar_s3_bucket;
            """
        ),
    ]
