# Generated by Django 5.2.7 on 2025-11-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_user_avatar_s3_bucket_user_avatar_s3_key_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE administration_subresource 
                ADD COLUMN IF NOT EXISTS description VARCHAR(200) DEFAULT '',
                ADD COLUMN IF NOT EXISTS icon VARCHAR(50) DEFAULT '';
            """,
            reverse_sql="""
                ALTER TABLE administration_subresource 
                DROP COLUMN IF EXISTS description,
                DROP COLUMN IF EXISTS icon;
            """
        ),
    ]
