# Generated by Django 5.2.7 on 2025-11-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_add_subresource_fields'),
    ]

    operations = [
        # Recursos y subrecursos completos del ecommerce
        migrations.RunSQL(
            sql="""
                -- Recurso 1: Inicio
                INSERT INTO administration_resource (name, description, "order", icon) VALUES ('Inicio', 'Panel principal y dashboard', 1, 'pi-home');
                INSERT INTO administration_subresource (resource_id, name, description, url, icon, "order") 
                VALUES (currval('"si2-ecommerce".security_resource_id_seq'), 'Dashboard', 'Panel de control principal', '/admin/dashboard', 'pi-chart-line', 1);
                
                -- Recurso 2: Catálogo
                INSERT INTO administration_resource (name, description, "order", icon) VALUES ('Catálogo', 'Gestión de productos y categorías', 2, 'pi-box');
                INSERT INTO administration_subresource (resource_id, name, description, url, icon, "order") 
                VALUES 
                    (currval('"si2-ecommerce".security_resource_id_seq'), 'Productos', 'Lista y gestión de productos', '/admin/catalog/products', 'pi-box', 1),
                    (currval('"si2-ecommerce".security_resource_id_seq'), 'Categorías', 'Categorías de productos', '/admin/catalog/categories', 'pi-sitemap', 2),
                    (currval('"si2-ecommerce".security_resource_id_seq'), 'Atributos', 'Atributos y variantes', '/admin/catalog/attributes', 'pi-tags', 3);
                
                -- Recurso 3: Inventario
                INSERT INTO administration_resource (name, description, "order", icon) VALUES ('Inventario', 'Control de stock y almacenes', 3, 'pi-database');
                INSERT INTO administration_subresource (resource_id, name, description, url, icon, "order") 
                VALUES 
                    (currval('"si2-ecommerce".security_resource_id_seq'), 'Stock', 'Estado actual de inventario', '/admin/inventory/stock', 'pi-list', 1),
                    (currval('"si2-ecommerce".security_resource_id_seq'), 'Almacenes', 'Gestión de almacenes', '/admin/inventory/warehouses', 'pi-building', 2),
                    (currval('"si2-ecommerce".security_resource_id_seq'), 'Movimientos', 'Historial de movimientos', '/admin/inventory/movements', 'pi-arrow-right-arrow-left', 3),
                    (currval('"si2-ecommerce".security_resource_id_seq'), 'Ajustes', 'Ajustes de inventario', '/admin/inventory/adjustments', 'pi-sliders-h', 4);
                
                -- Recurso 4: Ventas
                INSERT INTO administration_resource (name, description, "order", icon) VALUES ('Ventas', 'Gestión de pedidos y pagos', 4, 'pi-shopping-cart');
                INSERT INTO administration_subresource (resource_id, name, description, url, icon, "order") 
                VALUES 
                    (currval('"si2-ecommerce".security_resource_id_seq'), 'Pedidos', 'Listado de pedidos', '/admin/sales/orders', 'pi-shopping-cart', 1),
                    (currval('"si2-ecommerce".security_resource_id_seq'), 'Pagos', 'Historial de pagos', '/admin/sales/payments', 'pi-dollar', 2),
                    (currval('"si2-ecommerce".security_resource_id_seq'), 'Envíos', 'Gestión de envíos', '/admin/sales/shipments', 'pi-send', 3);
                
                -- Recurso 5: Clientes
                INSERT INTO administration_resource (name, description, "order", icon) VALUES ('Clientes', 'Gestión de clientes', 5, 'pi-users');
                INSERT INTO administration_subresource (resource_id, name, description, url, icon, "order") 
                VALUES 
                    (currval('"si2-ecommerce".security_resource_id_seq'), 'Clientes', 'Base de datos de clientes', '/admin/customers', 'pi-user', 1),
                    (currval('"si2-ecommerce".security_resource_id_seq'), 'Direcciones', 'Direcciones de envío', '/admin/customers/addresses', 'pi-map-marker', 2);
                
                -- Recurso 6: Analytics
                INSERT INTO administration_resource (name, description, "order", icon) VALUES ('Analytics', 'Análisis y reportes con IA', 6, 'pi-chart-bar');
                INSERT INTO administration_subresource (resource_id, name, description, url, icon, "order") 
                VALUES 
                    (currval('"si2-ecommerce".security_resource_id_seq'), 'Reportes IA', 'Reportes generados por IA', '/admin/analytics/ai-reports', 'pi-sparkles', 1),
                    (currval('"si2-ecommerce".security_resource_id_seq'), 'Predicciones', 'Forecasting de ventas', '/admin/analytics/forecasting', 'pi-chart-line', 2),
                    (currval('"si2-ecommerce".security_resource_id_seq'), 'Estadísticas', 'Estadísticas generales', '/admin/analytics/stats', 'pi-chart-bar', 3);
                
                -- Recurso 7: Administración
                INSERT INTO administration_resource (name, description, "order", icon) VALUES ('Administración', 'Configuración del sistema', 7, 'pi-cog');
                INSERT INTO administration_subresource (resource_id, name, description, url, icon, "order") 
                VALUES 
                    (currval('"si2-ecommerce".security_resource_id_seq'), 'Usuarios', 'Gestión de usuarios', '/admin/administration/users', 'pi-user', 1),
                    (currval('"si2-ecommerce".security_resource_id_seq'), 'Roles', 'Roles y permisos', '/admin/administration/roles', 'pi-shield', 2);
            """,
            reverse_sql="""
                DELETE FROM administration_subresource;
                DELETE FROM administration_resource;
            """
        ),
    ]
