# Generated by Django 5.2.7 on 2025-11-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_populate_menu_resources'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                -- Crear grupo ADMIN si no existe
                INSERT INTO auth_group (name) 
                VALUES ('ADMIN')
                ON CONFLICT (name) DO NOTHING;
                
                -- Crear rol ADMIN vinculado al grupo
                INSERT INTO administration_role (name, description, group_id)
                SELECT 'ADMIN', 'Administrador con acceso completo al sistema', id
                FROM auth_group WHERE name = 'ADMIN'
                ON CONFLICT (name) DO NOTHING;
                
                -- Asignar todos los subrecursos al rol ADMIN
                INSERT INTO administration_role_resource (role_id, resource_id, subresource_id)
                SELECT 
                    r.id as role_id,
                    res.id as resource_id,
                    sub.id as subresource_id
                FROM administration_role r
                CROSS JOIN administration_resource res
                CROSS JOIN administration_subresource sub
                WHERE r.name = 'ADMIN' 
                AND sub.resource_id = res.id
                ON CONFLICT (role_id, resource_id, subresource_id) DO NOTHING;
            """,
            reverse_sql="""
                DELETE FROM administration_role_resource 
                WHERE role_id IN (SELECT id FROM administration_role WHERE name = 'ADMIN');
                
                DELETE FROM administration_role WHERE name = 'ADMIN';
                DELETE FROM auth_group WHERE name = 'ADMIN';
            """
        ),
    ]
