# Generated by Django 5.2.7 on 2025-11-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('model_type', models.CharField(default='RandomForest', max_length=50)),
                ('file_path', models.CharField(help_text='Path al archivo .joblib del modelo', max_length=400)),
                ('mae', models.FloatField(blank=True, null=True, verbose_name='Mean Absolute Error')),
                ('rmse', models.FloatField(blank=True, null=True, verbose_name='Root Mean Squared Error')),
                ('r2_score', models.FloatField(blank=True, null=True, verbose_name='R² Score')),
                ('training_date_from', models.DateField(blank=True, null=True)),
                ('training_date_to', models.DateField(blank=True, null=True)),
                ('features_used', models.TextField(blank=True, help_text='JSON de features usadas')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modelo de Predicción',
                'verbose_name_plural': 'Modelos de Predicción',
                'db_table': 'analytics_forecast_model',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('SALES_BY_DATE', 'Ventas por Fecha'), ('SALES_BY_PRODUCT', 'Ventas por Producto'), ('SALES_BY_CATEGORY', 'Ventas por Categoría'), ('SALES_BY_CUSTOMER', 'Ventas por Cliente'), ('INVENTORY_STATUS', 'Estado de Inventario'), ('CUSTOM', 'Personalizado')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('JSON', 'JSON')], max_length=10)),
                ('filters', models.TextField(blank=True, help_text='JSON con filtros aplicados')),
                ('generated_by', models.CharField(blank=True, max_length=150)),
                ('file_path', models.CharField(blank=True, max_length=400)),
                ('file_size', models.IntegerField(blank=True, help_text='Tamaño en bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'analytics_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(blank=True, max_length=160)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=120)),
                ('variant_id', models.IntegerField(blank=True, null=True)),
                ('variant_code', models.CharField(blank=True, max_length=64)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=160)),
                ('qty', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hecho de Venta',
                'verbose_name_plural': 'Hechos de Ventas',
                'db_table': 'analytics_sale_fact',
                'indexes': [models.Index(fields=['date'], name='analytics_s_date_c24ec7_idx'), models.Index(fields=['product_id', 'date'], name='analytics_s_product_81eb70_idx'), models.Index(fields=['category_id', 'date'], name='analytics_s_categor_921d32_idx'), models.Index(fields=['customer_id', 'date'], name='analytics_s_custome_1c268d_idx'), models.Index(fields=['date', 'product_id', 'variant_id'], name='analytics_s_date_af95ab_idx')],
            },
        ),
    ]
