# Generated by Django 5.2.7 on 2025-11-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='s3_bucket',
            field=models.CharField(blank=True, help_text='Bucket S3 donde está almacenada la imagen', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='s3_key',
            field=models.CharField(blank=True, help_text='Key (path) de la imagen en S3', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.CharField(blank=True, help_text='URL directa de la imagen (fallback si no usa S3)', max_length=400, null=True),
        ),
    ]
