# Generated by Django 5.2.7 on 2025-11-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Clave de idempotencia para evitar pagos duplicados', max_length=120),
        ),
    ]
