# Generated by Django 5.2.7 on 2025-11-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_order_customer_alter_cart_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Instrucciones de entrega o comentarios del cliente', max_length=500, null=True),
        ),
    ]
